# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and https://github.com/craigcitro/r-travis/wiki
#
# I am adding bioc_packages to see if they are (hopefully) cached somewhere?
#
# Timing: Total time is 46 mins(!)
#
#   * ~ 6 minutes to get to the stage where we are building bioconductor
#   * ~ 20 minutes (1220 seconds) to build bioc and dependencies
#   * ~ 1.5 mins to build multiGSEA
#   * ~ 11 mins to run R CMD check
#
# packages
#
# Modeling this after the waldronlab/MultiAssayExperiment/.travis.yml
language: r
dist: trusty
sudo: required
cache: packages
warnings_are_errors: false

r:
  - bioc-devel

branches:
  only:
    - master
    - develop

r_binary_packages:
  - ggplot2
  - data.table
  - irlba
  - magrittr
  - Matrix
  - matrixStats
  - plotly
  - reshape2
  - viridis
  - dplyr
  - dtplyr
  - knitr
  - statmod
  - testthat
  - webshot
  - RcppArmadillo
  - RSQLite
  - hms
  - progress
  - formatR
  - bitops
  - bit
  - prettyunits
  - backports
  - checkmate
  - rstudioapi
  - lambda.r
  - futile.options
  - shape
  - rjson
  - RCurl
  - bit64
  - blob
  - memoise
  - xfun
  - tinytex
  - rprojroot
  - Formula
  - latticeExtra
  - acepack
  - futile.logger
  - snow
  - locfit
  - XML
  - shinythemes
  - rmarkdown
  - fastmatch
  - BiasedUrn
# These r-cran-packages are not available for install, so they will be installed
# manually during the bioc installation.
#  - circlize
#  - GetoptLong
#  - GlobalOptions
#  - bookdown
#  - BioocManager
#  - Hmisc (depends on r-recommended and r-cran-nnet which won't be installed)
#  - htmlTable (depends on r-recommended)

bioc_packages:
  - BiocGenerics
  - BiocParallel
  - Biobase
  - ComplexHeatmap
  - DelayedMatrixStats
  - limma
  - edgeR
  - GSEABase
  - GSVA
  - AnnotationDbi
  - BiocStyle
  - DESeq2
  - fgsea
  - GO.db
  - goseq
  - org.Hs.eg.db
  - org.Mm.eg.db
  - PANTHER.db
  - reactome.db
  - SummarizedExperiment
