# on: [push, pull_request]
on:
  push:
    branches:
      - master
      - develop # This will eventually require a different container
    paths:
      - 'R/**'
      - 'DESCRIPTION'
      - 'NAMESPACE'
      - 'src/**'
      - 'tests/**'
  pull_request:
  schedule:
    # Rerun checks daily, after facilebio/facilebio_base is rebuilt.
    # This will catch failures due to changes in functionality of packages
    # we depend on.
    # facilebio_base builds every day at 1AM pacific and takes about 1 hour
    # this runs at same time as facilebio_base_extra
    - cron: '0 11 * * *'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: facilebio/facilebio_base
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'develop'

      - name: Setup R
        uses: r-lib/actions/setup-r@2fac31217e602dd30286b4c984a0ccf1afb18cbd
        with:
          install-r: false

      # I guess I didn't want to install this into the base
      - name: Install dependencies
        run: remotes::install_deps(dependencies = TRUE, upgrade = FALSE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
